spring:
  datasource:
    url: jdbc:h2:mem:cs
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 20

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database: h2
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 50
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 50
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
